name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests automatisés
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
      
      - name: Installer Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Installer Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Installer les dépendances
        run: poetry install
      
      - name: Lancer les tests
        run: poetry run pytest tests/test_api.py -v